In [21]:
import numpy as np
import pandas as pd

### 1. Write a Pandas program to change the order of index of a given series.


In [26]:
data = np.random.rand(10)
ser = pd.Series(data,index=range(1,len(data)+1))
ser

1     0.827624
2     0.476496
3     0.678741
4     0.860655
5     0.961728
6     0.281991
7     0.250099
8     0.809585
9     0.049480
10    0.321515
dtype: float64

### 2. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [38]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
print('Addition')
print(s1+s2)
print('Subtraction')
print(s1-s2)
print('Multiplication')
print(s1*s2)
print('Division')
print(s1/s2)

Addition
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


### 3. Write a Python program to convert a Pandas module Series to Python list  and it's type

In [45]:
ser = pd.Series(np.random.randn(10))
x = list(ser.values)
x

[-0.88602036012498,
 -2.644149751755274,
 1.5285203760339428,
 -0.266076861232065,
 0.1557598966140622,
 -0.5761024102942842,
 2.172687342751156,
 -0.9052458822075621,
 0.3219642976649877,
 0.027053500461835713]

### 4. Write a Pandas program to select the rows where the score is missing, i.e. is NaN

Sample Python dictionary data and list labels:

    exam_data = {'name': ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor',   
    'Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 

In [199]:
exam_data = {'name': ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor',   'Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
            'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
            'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 
df = pd.DataFrame(exam_data,index=labels)
df[df['score'].isnull()]

name  score  attempts qualify
d  Johnson    NaN         3      no
h   Kambli    NaN         1      no

### 5. Write a Pandas program to create todays date


In [210]:
date = pd.datetime.today().date()
print(date)

2019-12-07


### 6.Write a Pandas program to create a Pivot table, by considering Titanic Dataset

In [237]:
data = pd.read_excel('titanic.xlsx')
pd.pivot_table(data,index = "Pclass", values = "Age", aggfunc = np.mean)

Age
Pclass           
1       38.233441
2       29.877630
3       25.140620

### 7.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10


In [212]:
np.array(np.arange(2,11).reshape(3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 8.Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [213]:
y = np.array(np.arange(9).reshape(3,3))
a = y.flatten()
b = y.ravel()
print('Original  :')
print(y,'\n')
print(a,'\n')
print(b,'\n')
y[0][2] = 999
print('Modified  : ')
print(y,'\n')
print(a,'\n')
print(b,'\n')

Original  :
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8] 

[0 1 2 3 4 5 6 7 8] 

Modified  : 
[[  0   1 999]
 [  3   4   5]
 [  6   7   8]] 

[0 1 2 3 4 5 6 7 8] 

[  0   1 999   3   4   5   6   7   8] 



### 9.Create a 3×3 numpyarray, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.

In [214]:
arr = np.array(np.arange(1,10).reshape(3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [215]:
print('Row Max : ',arr.max(axis=0))
print('Indices : ',arr.argmax(axis=0))

Row Max :  [7 8 9]
Indices :  [2 2 2]


In [216]:
print('Column Max : ',arr.max(axis=1))
print('Indices : ',arr.argmax(axis=1))

Column Max :  [3 6 9]
Indices :  [2 2 2]


In [217]:
print('Standard Deviation : ',np.std(arr))

Standard Deviation :  2.581988897471611


In [218]:
print('Cumulative Sum : ',arr.cumsum())

Cumulative Sum :  [ 1  3  6 10 15 21 28 36 45]


In [219]:
print('Cumulative Product : ',arr.cumprod())

Cumulative Product :  [     1      2      6     24    120    720   5040  40320 362880]


### 10.Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.