## NumPy

- Numerical Python
- To work on numerical data
- Converts the data into an array format

In [1]:
# Generate some random data
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.82133582, -0.83518877, -1.71969419],
       [-0.26007336,  0.70565363, -1.22168532]])

In [2]:
data*10

array([[  8.21335824,  -8.35188767, -17.19694194],
       [ -2.60073362,   7.05653631, -12.21685318]])

In [3]:
data + data

array([[ 1.64267165, -1.67037753, -3.43938839],
       [-0.52014672,  1.41130726, -2.44337064]])

In [4]:
data * data

array([[0.67459254, 0.69754028, 2.95734812],
       [0.06763815, 0.49794705, 1.49251502]])

In [5]:
data - data

array([[0., 0., 0.],
       [0., 0., 0.]])

### Arithmetic with NumPy

In [6]:
arr = np.array([[1,2,3],[2,3,1]])
arr

array([[1, 2, 3],
       [2, 3, 1]])

In [7]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.        ]])

In [8]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 1.        ]])

In [9]:
arr2 = np.array([[2,5,6],[1,2,0]])
arr2

array([[2, 5, 6],
       [1, 2, 0]])

In [10]:
arr2>arr

array([[ True,  True,  True],
       [False, False, False]])

In [11]:
np.random.random(10)

array([0.85924825, 0.30220415, 0.20967651, 0.31469292, 0.1530581 ,
       0.64465564, 0.90374359, 0.2946168 , 0.9247894 , 0.80257692])

In [12]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[5]

5

In [14]:
b[5:8]

array([5, 6, 7])

In [15]:
b[5:8]=12
b

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [16]:
arr_slice = b[5:8]
arr_slice

array([12, 12, 12])

In [17]:
arr_slice[1]=12345 ## original array also changes
arr_slice

array([   12, 12345,    12])

In [18]:
b

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
c = b.copy() ## copy() method does not affect the original array
c

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [20]:
b[0]=333
b

array([  333,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [21]:
c

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [22]:
arr_slice[:]=64
arr_slice

array([64, 64, 64])

In [23]:
b

array([333,   1,   2,   3,   4,  64,  64,  64,   8,   9])

### Two Dimenstional Array

In [24]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[2:,1:]

array([[8, 9]])

In [27]:
arr2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [28]:
arr2d[1,:2]

array([4, 5])

In [29]:
arr2d[:2,2]

array([3, 6])

In [30]:
arr2d[:2,1]

array([2, 5])

In [31]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [32]:
arr2d[:1,:]

array([[1, 2, 3]])

In [33]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [34]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [35]:
data = np.random.randn(7,4)
data

array([[-0.55909787,  0.06352726,  1.30924893, -1.00362096],
       [ 0.55680875,  0.30869914,  0.171086  ,  0.69686236],
       [ 0.10612762, -0.09766046, -1.27605656, -0.03458864],
       [-0.38546215, -0.00402214, -1.06474302, -2.35811498],
       [ 1.80048791, -1.14875643, -1.14093043, -0.63170622],
       [ 0.02658128,  0.62445525,  0.87647238,  0.29728531],
       [ 0.26039161, -0.89658892,  1.10725576, -0.02077297]])

In [36]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [37]:
data[names=='Bob']

array([[-0.55909787,  0.06352726,  1.30924893, -1.00362096],
       [-0.38546215, -0.00402214, -1.06474302, -2.35811498]])

In [38]:
data[names=='Bob',2:]

array([[ 1.30924893, -1.00362096],
       [-1.06474302, -2.35811498]])

In [39]:
data[names=='Bob',3]

array([-1.00362096, -2.35811498])

In [40]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [41]:
data[~(names=='Bob')]

array([[ 0.55680875,  0.30869914,  0.171086  ,  0.69686236],
       [ 0.10612762, -0.09766046, -1.27605656, -0.03458864],
       [ 1.80048791, -1.14875643, -1.14093043, -0.63170622],
       [ 0.02658128,  0.62445525,  0.87647238,  0.29728531],
       [ 0.26039161, -0.89658892,  1.10725576, -0.02077297]])

In [42]:
proc2 = names == 'Bob'
data[~proc2]

array([[ 0.55680875,  0.30869914,  0.171086  ,  0.69686236],
       [ 0.10612762, -0.09766046, -1.27605656, -0.03458864],
       [ 1.80048791, -1.14875643, -1.14093043, -0.63170622],
       [ 0.02658128,  0.62445525,  0.87647238,  0.29728531],
       [ 0.26039161, -0.89658892,  1.10725576, -0.02077297]])

In [43]:
data

array([[-0.55909787,  0.06352726,  1.30924893, -1.00362096],
       [ 0.55680875,  0.30869914,  0.171086  ,  0.69686236],
       [ 0.10612762, -0.09766046, -1.27605656, -0.03458864],
       [-0.38546215, -0.00402214, -1.06474302, -2.35811498],
       [ 1.80048791, -1.14875643, -1.14093043, -0.63170622],
       [ 0.02658128,  0.62445525,  0.87647238,  0.29728531],
       [ 0.26039161, -0.89658892,  1.10725576, -0.02077297]])

In [44]:
cols = np.array(['siri','sindhu','keerthi','siri'])
data[:,cols=='siri']

array([[-0.55909787, -1.00362096],
       [ 0.55680875,  0.69686236],
       [ 0.10612762, -0.03458864],
       [-0.38546215, -2.35811498],
       [ 1.80048791, -0.63170622],
       [ 0.02658128,  0.29728531],
       [ 0.26039161, -0.02077297]])

In [45]:
mask = (names=='Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [46]:
data[mask]

array([[-0.55909787,  0.06352726,  1.30924893, -1.00362096],
       [ 0.10612762, -0.09766046, -1.27605656, -0.03458864],
       [-0.38546215, -0.00402214, -1.06474302, -2.35811498],
       [ 1.80048791, -1.14875643, -1.14093043, -0.63170622]])

In [47]:
data[data<0]=0
data

array([[0.        , 0.06352726, 1.30924893, 0.        ],
       [0.55680875, 0.30869914, 0.171086  , 0.69686236],
       [0.10612762, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.80048791, 0.        , 0.        , 0.        ],
       [0.02658128, 0.62445525, 0.87647238, 0.29728531],
       [0.26039161, 0.        , 1.10725576, 0.        ]])

In [48]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.55680875, 0.30869914, 0.171086  , 0.69686236],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.02658128, 0.62445525, 0.87647238, 0.29728531],
       [0.26039161, 0.        , 1.10725576, 0.        ]])

### Fancy Indexing

In [49]:
arr = np.empty((8,4)) ## 8x4 garbage values
arr

array([[1.61325324e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307],
       [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        4.00536722e-307],
       [6.89798700e-307, 3.33775509e-307, 4.45047026e-307,
        3.44898162e-307],
       [1.11258871e-307, 3.56036942e-307, 3.33773471e-307,
        4.00541135e-307],
       [6.89801416e-307, 3.33772792e-307, 1.16820622e-307,
        2.78134232e-307],
       [2.78150360e-307, 4.00536722e-307, 4.45041934e-307,
        2.33647355e-307],
       [1.00133501e-307, 1.14589554e-312, 6.89803114e-307,
        2.33646676e-307],
       [3.56044072e-307, 1.00133501e-307, 1.01857546e-312,
        5.78296122e+067]])

In [51]:
for i in range(8):
    arr[i]=i ## updating array with required values
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [66]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [69]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [75]:
arr[[1,5,7,2]][:,[0,3,1,2]] ### Re-ordering the columns

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [76]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Concatenating and Splitting

In [88]:
arr = np.arange(16).reshape(2,2,4) ## 2 matrices containing 2 rows and 4 columns each
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

**array.transpose(*axes)** : 

- reshape(2,2,4)
    - index  value <br>
        0     2 --> number of matrices <br>
        1     2 --> number of rows   <br>
        2     4 --> number of columns <br>
- transpose(1,0,2)
    - index  value  new index  new value
        0     2        1         2 --> number of matrices
        1     2        0         2 --> number of rows
        2     4        2         4 --> number of columns

In [99]:
![]('transpose.JPG')

'[]' is not recognized as an internal or external command,
operable program or batch file.


In [90]:
arr.transpose(1,0,2) 

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr.transpose(2,0,1)

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])